server:
  port: 8011
spring:
  #热部署的开启
#  devtools:
#    restart:
#      additional-paths: src/main/resources
  application:
    name: dm-user-consumer

    # 配置 redis
  redis:
    # redis 数据库索引（默认为0）
    database: 0
    # redis 连接端口
    port: 6379
    # redis 服务地址
    host:   127.0.0.1   #192.168.42.100
    # 连接超时时间 （毫秒）
    timeout: 5000
    # redis 服务器链接密码 （默认为空）
    # password:
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
    #rabbitmq 中间件  消息队列
  rabbitmq:
    host:  127.0.0.1  #192.168.42.100
    port: 5672
    username: guest
    password: guest
#    publisher-returns: true
#    publisher-confirms: true
feign:
  hystrix:
    enabled: true # 开启熔断器

    #自定义配置 阿里云短信
aliyun:
  sms:
    accessKeyId: LTAI4GHEJQUvb59sRZwSAdQi
    accessKeySecret: ZVsh1f1ylNLDfOwoOeocIaJCBNo6PL
    template_code: SMS_189621954
    sign_name: 邯郸翱翔